//
// Generated file, do not edit! Created by nedtool 5.6 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>message.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Message
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int seqNum;
 *     string payload;
 *     char parity;
 *     int frameType;
 *     int ackNum;
 * }
 * </pre>
 *
 * Message_Base is only useful if it gets subclassed, and Message is derived from it.
 * The minimum code to be written for Message is the following:
 *
 * <pre>
 * class Message : public Message_Base
 * {
 *   private:
 *     void copy(const Message& other) { ... }

 *   public:
 *     Message(const char *name=nullptr, short kind=0) : Message_Base(name,kind) {}
 *     Message(const Message& other) : Message_Base(other) {copy(other);}
 *     Message& operator=(const Message& other) {if (this==&other) return *this; Message_Base::operator=(other); copy(other); return *this;}
 *     virtual Message *dup() const override {return new Message(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Message_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Message)
 * </pre>
 */
class Message_Base : public ::omnetpp::cPacket
{
  protected:
    int seqNum;
    ::omnetpp::opp_string payload;
    char parity;
    int frameType;
    int ackNum;

  private:
    void copy(const Message_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Message_Base&);


  public:
    virtual ~Message_Base();
    Message_Base(const char *name=nullptr, short kind=0);
    Message_Base(const Message_Base& other);
    // make assignment operator protected to force the user override it
    Message_Base& operator=(const Message_Base& other);
    virtual Message_Base *dup() const override {
        return new Message_Base(*this);
    }
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
    virtual char getParity() const;
    virtual void setParity(char parity);
    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);
    virtual int getAckNum() const;
    virtual void setAckNum(int ackNum);
};


#endif // ifndef __MESSAGE_M_H

